apiVersion: apps/v1
kind: Deployment
metadata:
  name: p16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p16
  template:
    metadata:
      labels:
        app: p16
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p16
        ports:
        - containerPort: 80
